# Generated by Django 4.1.3 on 2022-12-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_billing_address_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Postal', 'Postal')], default='Normal', max_length=60),
        ),
    ]
