# Generated by Django 4.1.3 on 2022-12-08 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='type',
            new_name='entrega',
        ),
    ]
