# Generated by Django 4.1.3 on 2022-12-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(default=1, upload_to='products/'),
            preserve_default=False,
        ),
    ]
